federation_version: 2
subgraphs:
  auth:
    routing_url: http://localhost:4001/
    schema:
      file: ./subgraph-auth/auth.graphql
  customers:
    routing_url: http://localhost:4002/
    schema:
      file: ./subgraph-customers/customers.graphql
  products:
    routing_url: http://localhost:4003/
    schema:
      file: ./subgraph-products/products.graphql
