federation_version: 2
subgraphs:
  storefront:
    routing_url: http://localhost:4001/
    schema:
      file: ./subgraph-storefront/storefront.graphql
  customers:
    routing_url: http://localhost:4002/
    schema:
      file: ./subgraph-customers/customers.graphql
  catalog:
    routing_url: http://localhost:4003/
    schema:
      file: ./subgraph-catalog/catalog.graphql
  storeLogs:
    routing_url: http://localhost:4009/
    schema:
      file: ./subgraph-storeLogs/storeLogs.graphql