federation_version: 2
subgraphs:
  admin:
    routing_url: http://localhost:4001/
    schema:
      file: ./subgraph-admin/admin.graphql
  checkout:
    routing_url: http://localhost:4002/
    schema:
      file: ./subgraph-checkout/checkout.graphql
  product:
    routing_url: http://localhost:4003/
    schema:
      file: ./subgraph-product/product.graphql
